GRID_SIZE = 9
BOX_SIZE = 3

DIFFICULTY_EASY = "easy"
DIFFICULTY_INTERMEDIATE = "intermediate"
DIFFICULTY_DIFFICULT = "difficult"

SCORE_WIN = {
    DIFFICULTY_EASY: 2,
    DIFFICULTY_INTERMEDIATE: 4,
    DIFFICULTY_DIFFICULT: 8,
}

SCORE_INTERRUPT = {
    DIFFICULTY_EASY: -1,
    DIFFICULTY_INTERMEDIATE: -2,
    DIFFICULTY_DIFFICULT: -3,
}

SCORES_FILE = "data/scores.json"
SAVE_FILE = "data/save.json"
GRIDS_DIR = "grids"
